SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS TOTAL_SALES
FROM BOOK A, AUTHOR B, BOOK_SALES C
WHERE A.BOOK_ID = C.BOOK_ID AND A.AUTHOR_ID = B.AUTHOR_ID
      AND TO_CHAR(C.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;
