SELECT DISTINCT B.USER_ID
       , B.NICKNAME
       , B.CITY||' '|| B.STREET_ADDRESS1||' '||B.STREET_ADDRESS2 AS "전체주소"
       , SUBSTR(TLNO,1,3)||'-'||SUBSTR(TLNO,4,4)||'-'||SUBSTR(TLNO,8) AS "전화번호"
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
WHERE B.USER_ID IN (SELECT B.USER_ID
                    FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
                    ON A.WRITER_ID = B.USER_ID
                    GROUP BY B.USER_ID
                    HAVING COUNT(*) >= 3
                   )
ORDER BY B.USER_ID DESC;
